project:
  type: website

website:
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme:
      light: [flatly, brand]
      dark: [darkly, brand]
    css: styles.css
    toc: false



