project:
  type: book

book:
  title: "Optimización"
  search: true
  page-footer: 
    left: "2026, Mauricio Mendiluce" 
  cover-image: cover.png
  chapters:
    - index.qmd
    - part: "Clases prácticas"
      chapters: 
        - clase_1.qmd
    - part: "Laboratorio"
      chapters: 
        - intro_julia.qmd
        - labo_1.qmd
        - labo_2.qmd
        - labo_3.qmd
        - labo_4.qmd
        - labo_5.qmd
        - labo_6.qmd
        - labo_7.qmd
        - labo_8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - brand



